# Generated by Django 3.2.2 on 2023-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0359_re2_linkifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='message_content_allowed_in_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realm',
            name='send_welcome_emails',
            field=models.BooleanField(default=False),
        ),
    ]
