# Generated by Django 3.2.2 on 2023-11-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0361_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rev_address',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
