# Generated by Django 3.2.2 on 2023-11-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0007_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmcreationkey',
            name='presume_email_valid',
            field=models.BooleanField(default=True),
        ),
    ]
