# Generated by Django 3.2.2 on 2023-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0008_alter_realmcreationkey_presume_email_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmcreationkey',
            name='presume_email_valid',
            field=models.BooleanField(default=False),
        ),
    ]
