version: '2.3'

x-rnode:
  &default-rnode
  image: $RNODE_IMAGE
  user: root
  restart: always

services:

  boot:
    << : *default-rnode
    container_name: boot
    command: run -s --validator-private-key $VALIDATOR_BOOT_PRIVATE --allow-private-addresses --host boot
              --protocol-port 40400 --discovery-port 40404
              --wallets-file /data-init/genesis/wallets.txt --bonds-file /data-init/genesis/bonds.txt
              --tls-certificate-path /data-init/node.certificate.pem --tls-key-path /data-init/node.key.pem
              --approve-duration 5seconds --approve-interval 5seconds
    ports:
    - $MY_NET_IP:40401:40401
    - $MY_NET_IP:40402:40402
    - $MY_NET_IP:40403:40403
    - $MY_NET_IP:40405:40405
    # Ports exposed externally
    - $MY_NET_IP:40400:40400
    - $MY_NET_IP:40404:40404
    volumes:
    - ./data-init:/data-init
    - ./data/rnode:/var/lib/rnode # expose RNOde data-dir to host

  read:
    << : *default-rnode
    container_name: read
    command: run -b "$VALIDATOR_BOOT_ADDRESS" --allow-private-addresses --host read --no-upnp
              --protocol-port 40410 --discovery-port 40414
              --approve-duration 5seconds --approve-interval 5seconds
              --fork-choice-check-if-stale-interval 15seconds --fork-choice-stale-threshold 15seconds
    ports:
    - $MY_NET_IP:40411:40401
    - $MY_NET_IP:40413:40403
    - $MY_NET_IP:40415:40405
    # Ports exposed externally
    - $MY_NET_IP:40410:40410
    - $MY_NET_IP:40414:40414
